version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file: 
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: '/var/log/roster/roster.log'
loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
